name = "CPUOptimizedConvNet"
uuid = "13bb932b-e154-4569-821b-dfe7ce7f25e9"
authors = ["Chris Elrod <elrodc@gmail.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1.4"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
